users for snapclient and snapserver daemon

diff --git a/client/debian/snapclient.postrm b/client/debian/snapclient.postrm
--- a/client/debian/snapclient.postrm
+++ b/client/debian/snapclient.postrm
@@ -3,15 +3,15 @@
 set -e
 
 if [ "$1" = "purge" ]; then
-	# clean up all statoverrides that belonged to snapcast, so the
-	# snapcast system user can be removed cleanly
-	for i in $(dpkg-statoverride --list | awk '/^snapcast / {print $4}'); do
+	# clean up all statoverrides that belonged to snapclient, so the
+	# snapclient system user can be removed cleanly
+	for i in $(dpkg-statoverride --list | awk '/^snapclient / {print $4}'); do
 		if dpkg-statoverride --list --quiet "$i" >/dev/null; then
 			dpkg-statoverride --force --quiet --remove "$i"
 		fi
 	done
 
-	deluser --quiet --system snapcast > /dev/null || true
+	deluser --quiet --system snapclient > /dev/null || true
 fi
 
 #DEBHELPER#
